name: Run flow
on:
  workflow_dispatch:
    inputs:
      prefect-version:
        description: Prefect version for flows
        required: true
        default: '2.*'
        type: string
      flow:
        description: Flow to run
        required: true
        type: choice
        options: ['web_to_gcs.py']
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          
      - name: Python dependencies
        run: |
          pip install -U prefect==2.*
          pip install -r requirements.txt
          pip install gspread google-auth google-auth-oauthlib google-auth-httplib2
      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{secrets.PREFECT_API_KEY}} 
          prefect cloud workspace set --workspace "${{secrets.PREFECT_WORKSPACE}}"
      
          
      - name: Load data into GCS

        run: |
          python flows/web_to_gcs.py
